name: ar_rtc_engine
description: Flutter plugin for anyRTC Video SDK.
version: 4.2.8
homepage: https://www.anyrtc.io

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.1
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: org.ar.rtc_engine
        pluginClass: ArRtcEnginePlugin
      ios:
        pluginClass: ArRtcEnginePlugin

