name: ar_rtc_engine
description: Flutter plugin for anyRTC Video SDK.
version: 4.2.4
homepage: https://www.anyrtc.io

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.6'
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.0
  
dev_dependencies:
  integration_test: ^1.0.2+2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
flutter:
  plugin:
    platforms:
      android:
        package: org.ar.rtc_engine
        pluginClass: ArRtcEnginePlugin
      ios:
        pluginClass: ArRtcEnginePlugin

